import { describe, it, expect } from 'vitest'
import { applyParams } from './ops'
import { labStatsFromLinear } from './stats'
import { fitMatch, matchStrength, averageStats } from './fit'
import { linearRgbToLab, deltaE2000 } from './color'
import { DEFAULT_PARAMS, type ControlParams, type LabStats, type LinearRGB } from './types'

function syntheticSource(): LinearRGB[] {
  const px: LinearRGB[] = []
  const vals = [0.08, 0.25, 0.45, 0.65, 0.85]
  for (const r of vals) for (const g of vals) for (const b of vals) px.push([r, g, b])
  return px
}

function medianDE(a: LinearRGB[], b: LinearRGB[]): number {
  const des = a.map((px, i) => {
    const l1 = linearRgbToLab(px)
    const l2 = linearRgbToLab(b[i])
    return deltaE2000(l1[0], l1[1], l1[2], l2[0], l2[1], l2[2])
  })
  des.sort((x, y) => x - y)
  return des[Math.floor(des.length / 2)]
}

describe('fit fidelity gate (the engine make-or-break)', () => {
  const source = syntheticSource()
  // Looks generated by the basis's fitted controls — the fit must invert them.
  const cases: Partial<ControlParams>[] = [
    { exposure: 20 },
    { temp: 30, tint: -15 },
    { exposure: -15, contrast: 25, saturation: 20 },
    { temp: -20, tint: 25, exposure: 10 },
    { contrast: 35 },
    { saturation: -30, temp: 15 },
  ]
  const medians: number[] = []

  for (const c of cases) {
    it(`recovers ${JSON.stringify(c)} within median ΔE2000 <= 3`, () => {
      const known: ControlParams = { ...DEFAULT_PARAMS, ...c }
      const ref = source.map((px) => applyParams(px, known))
      const target = labStatsFromLinear(ref)
      const fitted = fitMatch(source, target)
      const rendered = source.map((px) => applyParams(px, fitted))
      const m = medianDE(rendered, ref)
      medians.push(m)
      expect(m).toBeLessThanOrEqual(3)
    })
  }

  it('overall median across cases <= 3 (GATE)', () => {
    medians.sort((a, b) => a - b)
    expect(medians[Math.floor(medians.length / 2)]).toBeLessThanOrEqual(3)
  })

  it('match strength is >= 90 for a good fit', () => {
    const known: ControlParams = { ...DEFAULT_PARAMS, temp: 20, exposure: 10 }
    const ref = source.map((px) => applyParams(px, known))
    const target = labStatsFromLinear(ref)
    const fitted = fitMatch(source, target)
    const rendered = labStatsFromLinear(source.map((px) => applyParams(px, fitted)))
    expect(matchStrength(rendered, target)).toBeGreaterThanOrEqual(90)
  })
})

describe('mood-board average', () => {
  it('trims extremes when >= 4 refs', () => {
    const s = (L: number): LabStats => ({ mean: [L, 0, 0], std: [1, 1, 1] })
    // L = 10,50,50,90 -> trim 10 and 90 -> mean of 50,50 = 50
    expect(averageStats([s(10), s(50), s(50), s(90)]).mean[0]).toBeCloseTo(50, 6)
  })
})
